# Hotel Booking, Revenue and Cancellation Analysis

This notebook follows the **Hotel Booking, Revenue and Cancellation Analysis** requirements in the project assessment.

Workflow:
1. Understand the dataset
2. Clean the data
3. Create required analytical columns
4. Perform the required basic analysis
5. Export `cleaned_hotel_bookings.csv`

**Assessment-required columns created in this notebook:**
- `Total_Guests`
- `Stay_Nights`
- `Booking_Status`

## 1. Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2. Loading the Dataset

Place `hotel_bookings.csv` in the same folder as this notebook before running the cell below.

In [2]:
df = pd.read_csv("hotel_bookings.csv")
print("Dataset loaded successfully.")

Dataset loaded successfully.

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 119390
Columns: 32

## 3. Understand the Dataset

The assessment requires checking:
- Number of rows and columns
- Column names
- Data types
- Missing values
- Statistical information

In [4]:
# Dataset's dimensions
print("Dataset Shape:", df.shape)

# Column names
print("\nColumn Names:")
print(df.columns.tolist())

# First five records
print("\nFirst 5 Records:")
display(df.head())

# Last five records
print("\nLast 5 Records:")
display(df.tail())

Dataset Shape: (119390, 32)

Column Names:
['hotel', 'is_canceled', 'lead_time', 'arrival_date_year', 'arrival_date_month', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'meal', 'country', 'market_segment', 'distribution_channel', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'reserved_room_type', 'assigned_room_type', 'booking_changes', 'deposit_type', 'agent', 'company', 'days_in_waiting_list', 'customer_type', 'adr', 'required_car_parking_spaces', 'total_of_special_requests', 'reservation_status', 'reservation_status_date']

First 5 Records:

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

Last 5 Records:

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [5]:
# Data types
print("Data Types:")
display(df.dtypes.to_frame("Data Type"))

# Statistical information
print("\nStatistical Summary:")
display(df.describe(include="all").T)

# info
print("\nDataset Info:")
df.info()

Data Types:

                               Data Type
hotel                             object
is_canceled                        int64
lead_time                          int64
arrival_date_year                  int64
arrival_date_month                object
arrival_date_week_number           int64
arrival_date_day_of_month          int64
stays_in_weekend_nights            int64
stays_in_week_nights               int64
adults                             int64
children                         float64
babies                             int64
meal                              object
country                           object
market_segment                    object
distribution_channel              object
is_repeated_guest                  int64
previous_cancellations             int64
previous_bookings_not_canceled     int64
reserved_room_type                object
assigned_room_type                object
booking_changes                    int64
deposit_type                      object
agent                            float64
company                          float64
days_in_waiting_list               int64
customer_type                     object
adr                              float64
required_car_parking_spaces        int64
total_of_special_requests          int64
reservation_status                object
reservation_status_date           object

Statistical Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
hotel,119390,2,City Hotel,79330,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_canceled,119390.0,NaN,NaN,NaN,0.370416,0.482918,0.0,0.0,0.0,1.0,1.0
lead_time,119390.0,NaN,NaN,NaN,104.011416,106.863097,0.0,18.0,69.0,160.0,737.0
arrival_date_year,119390.0,NaN,NaN,NaN,2016.156554,0.707476,2015.0,2016.0,2016.0,2017.0,2017.0
arrival_date_month,119390,12,August,13877,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arrival_date_week_number,119390.0,NaN,NaN,NaN,27.165173,13.605138,1.0,16.0,28.0,38.0,53.0
arrival_date_day_of_month,119390.0,NaN,NaN,NaN,15.798241,8.780829,1.0,8.0,16.0,23.0,31.0
stays_in_weekend_nights,119390.0,NaN,NaN,NaN,0.927599,0.998613,0.0,0.0,1.0,2.0,19.0
stays_in_week_nights,119390.0,NaN,NaN,NaN,2.500302,1.908286,0.0,1.0,2.0,3.0,50.0
adults,119390.0,NaN,NaN,NaN,1.856403,0.579261,0.0,2.0,2.0,2.0,55.0
children,119386.0,NaN,NaN,NaN,0.10389,0.398561,0.0,0.0,0.0,0.0,10.0
babies,119390.0,NaN,NaN,NaN,0.007949,0.097436,0.0,0.0,0.0,0.0,10.0
meal,119390,5,BB,92310,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country,118902,177,PRT,48590,NaN,NaN,NaN,NaN,NaN,NaN,NaN
market_segment,119390,8,Online TA,56477,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distribution_channel,119390,5,TA/TO,97870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_repeated_guest,119390.0,NaN,NaN,NaN,0.031912,0.175767,0.0,0.0,0.0,0.0,1.0
previous_cancellations,119390.0,NaN,NaN,NaN,0.087118,0.844336,0.0,0.0,0.0,0.0,26.0
previous_bookings_not_canceled,119390.0,NaN,NaN,NaN,0.137097,1.497437,0.0,0.0,0.0,0.0,72.0
reserved_room_type,119390,10,A,85994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
assigned_room_type,119390,12,A,74053,NaN,NaN,NaN,NaN,NaN,NaN,NaN
booking_changes,119390.0,NaN,NaN,NaN,0.221124,0.652306,0.0,0.0,0.0,0.0,21.0
deposit_type,119390,3,No Deposit,104641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
agent,103050.0,NaN,NaN,NaN,86.693382,110.774548,1.0,9.0,14.0,229.0,535.0
company,6797.0,NaN,NaN,NaN,189.266735,131.655015,6.0,62.0,179.0,270.0,543.0
days_in_waiting_list,119390.0,NaN,NaN,NaN,2.321149,17.594721,0.0,0.0,0.0,0.0,391.0
customer_type,119390,4,Transient,89613,NaN,NaN,NaN,NaN,NaN,NaN,NaN
adr,119390.0,NaN,NaN,NaN,101.831122,50.53579,-6.38,69.29,94.575,126.0,5400.0
required_car_parking_spaces,119390.0,NaN,NaN,NaN,0.062518,0.245291,0.0,0.0,0.0,0.0,8.0
total_of_special_requests,119390.0,NaN,NaN,NaN,0.571363,0.792798,0.0,0.0,0.0,1.0,5.0
reservation_status,119390,3,Check-Out,75166,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reservation_status_date,119390,926,2015-10-21,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

# 4. Data Cleaning

## Check Missing Values

First inspecting the missing values before making any changes.

In [6]:
missing_values = df.isnull().sum()
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_summary = pd.DataFrame({
    "Missing Values": missing_values,
    "Missing Percentage": missing_percentage.round(2)
}).sort_values("Missing Values", ascending=False)

display(missing_summary[missing_summary["Missing Values"] > 0])

          Missing Values  Missing Percentage
company           112593               94.31
agent              16340               13.69
country              488                0.41
children               4                0.00

## Handle Missing Values

Based on the dataset,requirements and the project questions:

- **`children`**: missing values are treated as 0 because it is required for `Total_Guests`.
- **`country`**: missing values are retained as `"Unknown"` because country is required later for the top-5 completed-bookings analysis.
- **`agent`**: retained with missing values because it is not needed for the required business questions and there is no justified value to impute.
- **`company`**: removed because it has a very large number of missing values and is not required for the specified business questions.

No artificial identifier values are inserted into **`agent`** or **`company`**.

In [7]:
# Handles 'children'
df["children"] = df["children"].fillna(0)

# Handle 'country'
df["country"] = df["country"].fillna("Unknown")

# Remove 'company' because of extensive missingness and lack of relevance
# to the assessment's required questions.
df.drop(columns=["company"], inplace=True)

print("Missing values after initial handling:")
display(df.isnull().sum().sort_values(ascending=False).head(10))

Missing values after initial handling:

agent                       16340
is_canceled                     0
hotel                           0
arrival_date_year               0
arrival_date_month              0
arrival_date_week_number        0
lead_time                       0
stays_in_weekend_nights         0
stays_in_week_nights            0
adults                          0
dtype: int64

## Checking Duplicate Rows

In [8]:
duplicate_count = df.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 32001

In [9]:
# Remove exact duplicate rows
df = df.drop_duplicates().reset_index(drop=True)

print("Dataset shape after duplicate removal:", df.shape)
print("Remaining duplicate rows:", df.duplicated().sum())

Dataset shape after duplicate removal: (87389, 31)
Remaining duplicate rows: 0

## Correcting Data Types

For this dataset:
- `reservation_status_date` is a genuine date field and should be `datetime64[ns]`.
- `children` can be converted to integer after missing values are handled.
- The arrival year/month/week/day columns are **date components**, so they should not be converted individually to datetime.

The four arrival components are kept in their original appropriate types.

In [10]:
# Converting the genuine date column
df["reservation_status_date"] = pd.to_datetime(
    df["reservation_status_date"],
    errors="coerce"
)

# Converting children to integer after filling missing values
df["children"] = df["children"].astype(int)

print(df[[
    "children",
    "reservation_status_date"
]].dtypes)

children                            int64
reservation_status_date    datetime64[ns]
dtype: object

## Create a Complete Arrival Date

The dataset stores arrival date information in separate columns:
- `arrival_date_year`
- `arrival_date_month`
- `arrival_date_day_of_month`

Creating one additional `Arrival_Date` column for easier time-based analysis. Keep the original component columns as well.

In [11]:
df["Arrival_Date"] = pd.to_datetime(
    df["arrival_date_year"].astype(str)
    + "-"
    + df["arrival_date_month"]
    + "-"
    + df["arrival_date_day_of_month"].astype(str),
    format="%Y-%B-%d",
    errors="coerce"
)

display(df[[
    "arrival_date_year",
    "arrival_date_month",
    "arrival_date_day_of_month",
    "Arrival_Date"
]].head())

,arrival_date_year,arrival_date_month,arrival_date_day_of_month,Arrival_Date
0,2015,July,1,2015-07-01
1,2015,July,1,2015-07-01
2,2015,July,1,2015-07-01
3,2015,July,1,2015-07-01
4,2015,July,1,2015-07-01

## Check Invalid or Unusual Values

- Zero guests
- Zero-night stays
- Negative ADR
- Negative lead time
- Invalid cancellation indicator
- Invalid hotel values

In [12]:
print("Zero-guest records:", (df["adults"] + df["children"] + df["babies"] == 0).sum())
print("Zero-night records:",
      (df["stays_in_weekend_nights"] + df["stays_in_week_nights"] == 0).sum())
print("Negative ADR records:", (df["adr"] < 0).sum())
print("Negative lead-time records:", (df["lead_time"] < 0).sum())

print("\nUnexpected is_canceled values:",
      sorted(set(df["is_canceled"].dropna().unique()) - {0, 1}))

print("\nHotel values:")
print(df["hotel"].value_counts(dropna=False))

Zero-guest records: 166
Zero-night records: 651
Negative ADR records: 1
Negative lead-time records: 0

Unexpected is_canceled values: []

Hotel values:
hotel
City Hotel      53426
Resort Hotel    33963
Name: count, dtype: int64

### Treatment of unusual values

For the cleaning stage:
- Negative ADR values are invalid and are removed.
- Negative lead times are invalid and are removed.
- Records with zero guests are treated as invalid booking records and are removed.
- Zero-night stays are **not automatically deleted** because they can represent records that need business interpretation; they are flagged and retained unless the project decides otherwise.

In [13]:
# Removes clearly invalid numeric records
invalid_adr = df["adr"] < 0
invalid_lead_time = df["lead_time"] < 0
zero_guests = (
    df["adults"] +
    df["children"] +
    df["babies"]
) == 0

print("Rows removed for negative ADR:", invalid_adr.sum())
print("Rows removed for negative lead time:", invalid_lead_time.sum())
print("Rows removed for zero guests:", zero_guests.sum())

df = df.loc[
    ~(invalid_adr | invalid_lead_time | zero_guests)
].copy()

df.reset_index(drop=True, inplace=True)

Rows removed for negative ADR: 1
Rows removed for negative lead time: 0
Rows removed for zero guests: 166

# 5. Create Required New Columns

The project assessment specifically requires:
1. `Total_Guests`
2. `Stay_Nights`
3. `Booking_Status`

## `Total_Guests`

Logic:

`Adults + Children + Babies`

In [14]:
df["Total_Guests"] = (
    df["adults"] +
    df["children"] +
    df["babies"]
).astype(int)

display(df[[
    "adults",
    "children",
    "babies",
    "Total_Guests"
]].head(10))

   adults  children  babies  Total_Guests
0       2         0       0             2
1       2         0       0             2
2       1         0       0             1
3       1         0       0             1
4       2         0       0             2
5       2         0       0             2
6       2         0       0             2
7       2         0       0             2
8       2         0       0             2
9       2         0       0             2

## `Stay_Nights`

Logic:

`Weekend Nights + Week Nights`

In [15]:
df["Stay_Nights"] = (
    df["stays_in_weekend_nights"] +
    df["stays_in_week_nights"]
).astype(int)

display(df[[
    "stays_in_weekend_nights",
    "stays_in_week_nights",
    "Stay_Nights"
]].head(10))

   stays_in_weekend_nights  stays_in_week_nights  Stay_Nights
0                        0                     0            0
1                        0                     0            0
2                        0                     1            1
3                        0                     1            1
4                        0                     2            2
5                        0                     2            2
6                        0                     2            2
7                        0                     3            3
8                        0                     3            3
9                        0                     4            4

## `Booking_Status`

Mapping:
- `is_canceled = 0` → `Completed`
- `is_canceled = 1` → `Cancelled`

In [16]:
df["Booking_Status"] = df["is_canceled"].map({
    0: "Completed",
    1: "Cancelled"
})

display(df[[
    "is_canceled",
    "Booking_Status"
]].head(10))

   is_canceled Booking_Status
0            0      Completed
1            0      Completed
2            0      Completed
3            0      Completed
4            0      Completed
5            0      Completed
6            0      Completed
7            1      Cancelled
8            1      Cancelled
9            1      Cancelled

## Validate the New Columns

In [17]:
new_columns = [
    "Total_Guests",
    "Stay_Nights",
    "Booking_Status"
]

print("Missing values in new columns:")
display(df[new_columns].isnull().sum())

print("\nBooking status distribution:")
display(df["Booking_Status"].value_counts())

print("\nBasic statistics for new numeric columns:")
display(df[["Total_Guests", "Stay_Nights"]].describe())

Missing values in new columns:

Total_Guests      0
Stay_Nights       0
Booking_Status    0
dtype: int64

Booking status distribution:

Booking_Status
Completed    63213
Cancelled    24009
Name: count, dtype: int64

Basic statistics for new numeric columns:

       Total_Guests   Stay_Nights
count  87222.000000  87222.000000
mean       2.029167      3.628672
std        0.790139      2.742888
min        1.000000      0.000000
25%        2.000000      2.000000
50%        2.000000      3.000000
75%        2.000000      5.000000
max       55.000000     69.000000

# 6. Final Cleaning Validation

Before analysis, verifying that the cleaned dataset has:
- No exact duplicate rows
- No missing `country`
- No missing `children`
- No missing `Booking_Status`
- Correct date datatype
- No negative ADR
- No negative lead time
- No zero-guest records

In [18]:
validation = {
    "Duplicate rows": df.duplicated().sum(),
    "Missing country": df["country"].isnull().sum(),
    "Missing children": df["children"].isnull().sum(),
    "Missing Booking_Status": df["Booking_Status"].isnull().sum(),
    "Negative ADR": (df["adr"] < 0).sum(),
    "Negative lead time": (df["lead_time"] < 0).sum(),
    "Zero guests": (df["Total_Guests"] == 0).sum()
}

validation_df = pd.DataFrame(
    validation.items(),
    columns=["Check", "Count"]
)

display(validation_df)

print("reservation_status_date dtype:",
      df["reservation_status_date"].dtype)
print("Arrival_Date dtype:",
      df["Arrival_Date"].dtype)

                    Check  Count
0          Duplicate rows      0
1         Missing country      0
2        Missing children      0
3  Missing Booking_Status      0
4            Negative ADR      0
5      Negative lead time      0
6             Zero guests      0

reservation_status_date dtype: datetime64[ns]
Arrival_Date dtype: datetime64[ns]

# 7. Required Basic Analysis

The assessment requires these seven metrics:
1. Total bookings
2. Total cancelled bookings
3. Cancellation rate
4. Average Daily Rate (ADR)
5. Average stay duration
6. City Hotel bookings
7. Resort Hotel bookings

In [19]:
# Total bookings
total_bookings = len(df)

# Total cancelled bookings
total_cancelled = (
    df["Booking_Status"] == "Cancelled"
).sum()

# Cancellation rate
cancellation_rate = (
    total_cancelled / total_bookings
) * 100

# Average Daily Rate
average_adr = df["adr"].mean()

# Average stay duration
average_stay = df["Stay_Nights"].mean()

# City Hotel bookings
city_hotel_bookings = (
    df["hotel"] == "City Hotel"
).sum()

# Resort Hotel bookings
resort_hotel_bookings = (
    df["hotel"] == "Resort Hotel"
).sum()

summary_df = pd.DataFrame({
    "Metric": [
        "Total Bookings",
        "Total Cancelled Bookings",
        "Cancellation Rate (%)",
        "Average ADR",
        "Average Stay Duration (Nights)",
        "City Hotel Bookings",
        "Resort Hotel Bookings"
    ],
    "Value": [
        total_bookings,
        total_cancelled,
        round(cancellation_rate, 2),
        round(average_adr, 2),
        round(average_stay, 2),
        city_hotel_bookings,
        resort_hotel_bookings
    ]
})

display(summary_df)

                           Metric     Value
0                  Total Bookings  87222.00
1        Total Cancelled Bookings  24009.00
2           Cancellation Rate (%)     27.53
3                     Average ADR    106.52
4  Average Stay Duration (Nights)      3.63
5             City Hotel Bookings  53272.00
6           Resort Hotel Bookings  33950.00

## Additional Descriptive Analysis

These checks are not replacements for the seven required metrics. They provide useful context for later SQL, Excel and Power BI work.

In [20]:
print("Bookings by hotel:")
display(df["hotel"].value_counts())

print("\nBookings by customer type:")
display(df["customer_type"].value_counts())

print("\nBookings by booking status:")
display(df["Booking_Status"].value_counts())

print("\nTop 10 countries by bookings:")
display(df["country"].value_counts().head(10))

Bookings by hotel:

hotel
City Hotel      53272
Resort Hotel    33950
Name: count, dtype: int64

Bookings by customer type:

customer_type
Transient          71858
Transient-Party    11688
Contract            3135
Group                541
Name: count, dtype: int64

Bookings by booking status:

Booking_Status
Completed    63213
Cancelled    24009
Name: count, dtype: int64

Top 10 countries by bookings:

country
PRT    27351
GBR    10422
FRA     8823
ESP     7244
DEU     5385
ITA     3061
IRL     3015
BEL     2081
BRA     1993
NLD     1910
Name: count, dtype: int64

## Cancellation Rate by Hotel

This is useful for the business question: which hotel has the higher cancellation percentage?

In [21]:
hotel_cancellation = (
    df.groupby("hotel")
      .agg(
          Total_Bookings=("hotel", "size"),
          Cancelled_Bookings=("Booking_Status",
                             lambda x: (x == "Cancelled").sum())
      )
)

hotel_cancellation["Cancellation_Rate_%"] = (
    hotel_cancellation["Cancelled_Bookings"]
    / hotel_cancellation["Total_Bookings"]
    * 100
)

hotel_cancellation = hotel_cancellation.sort_values(
    "Cancellation_Rate_%",
    ascending=False
)

display(hotel_cancellation)

              Total_Bookings  Cancelled_Bookings  Cancellation_Rate_%
hotel
City Hotel             53272               16035            30.100240
Resort Hotel           33950                7974            23.487482

## Monthly Booking Summary

Displaying using `Arrival_Date` to create a month-level summary.

In [22]:
monthly_bookings = (
    df.groupby(
        df["Arrival_Date"].dt.month_name()
    )
    .size()
    .sort_values(ascending=False)
)

display(monthly_bookings.to_frame("Total Bookings"))

              Total Bookings
Arrival_Date
August                 11242
July                   10042
May                     8343
April                   7900
June                    7756
March                   7488
October                 6921
September               6681
February                6082
December                5111
November                4971
January                 4685

## Lead Time Category

cancellation analysis:
- 0 to 30 days
- 31 to 90 days
- 91 to 180 days
- More than 180 days

In [23]:
bins = [0, 30, 90, 180, np.inf]
labels = [
    "0-30 Days",
    "31-90 Days",
    "91-180 Days",
    "180+ Days"
]

df["Lead_Time_Category"] = pd.cut(
    df["lead_time"],
    bins=bins,
    labels=labels,
    include_lowest=True
)

lead_time_analysis = (
    df.groupby("Lead_Time_Category", observed=False)
      .agg(
          Total_Bookings=("Booking_Status", "size"),
          Cancelled_Bookings=(
              "Booking_Status",
              lambda x: (x == "Cancelled").sum()
          )
      )
)

lead_time_analysis["Cancellation_Rate_%"] = (
    lead_time_analysis["Cancelled_Bookings"]
    / lead_time_analysis["Total_Bookings"]
    * 100
)

display(lead_time_analysis)

                    Total_Bookings  Cancelled_Bookings  Cancellation_Rate_%
Lead_Time_Category
0-30 Days                    34522                5677            16.444586
31-90 Days                   22720                7280            32.042254
91-180 Days                  18224                6380            35.008780
180+ Days                    11756                4672            39.741409

# 8. Final Cleaned Dataset Profile

In [24]:
print("Final dataset shape:", df.shape)

print("\nFinal data types:")
display(df.dtypes.to_frame("Data Type"))

print("\nRemaining missing values:")
display(
    df.isnull().sum()
      .sort_values(ascending=False)
      .to_frame("Missing Values")
      .head(15)
)

Final dataset shape: (87222, 36)

Final data types:

                                     Data Type
hotel                                   object
is_canceled                              int64
lead_time                                int64
arrival_date_year                        int64
arrival_date_month                      object
arrival_date_week_number                 int64
arrival_date_day_of_month                int64
stays_in_weekend_nights                  int64
stays_in_week_nights                     int64
adults                                   int64
children                                 int64
babies                                   int64
meal                                    object
country                                 object
market_segment                          object
distribution_channel                    object
is_repeated_guest                        int64
previous_cancellations                   int64
previous_bookings_not_canceled           int64
reserved_room_type                      object
assigned_room_type                      object
booking_changes                          int64
deposit_type                            object
agent                                  float64
days_in_waiting_list                     int64
customer_type                           object
adr                                    float64
required_car_parking_spaces              int64
total_of_special_requests                int64
reservation_status                      object
reservation_status_date         datetime64[ns]
Arrival_Date                    datetime64[ns]
Total_Guests                             int64
Stay_Nights                              int64
Booking_Status                          object
Lead_Time_Category                    category

Remaining missing values:

                           Missing Values
agent                               12137
hotel                                   0
lead_time                               0
is_canceled                             0
arrival_date_year                       0
arrival_date_month                      0
arrival_date_day_of_month               0
arrival_date_week_number                0
stays_in_week_nights                    0
adults                                  0
children                                0
stays_in_weekend_nights                 0
meal                                    0
country                                 0
market_segment                          0

In [ ]:
# Agent contains missing values because some bookings were not associated
# with a recorded booking agent. Since agent information is not required
# for the project's main analysis, these missing values are retained rather
# than replaced with an arbitrary value.

# 9. Export Cleaned Dataset

`cleaned_hotel_bookings.csv`

In [25]:
output_file = "cleaned_hotel_bookings.csv"

df.to_csv(
    output_file,
    index=False
)

print(f"Cleaned dataset exported successfully as: {output_file}")

Cleaned dataset exported successfully as: cleaned_hotel_bookings.csv

# BeautifulSoup Web Scraping

## Objective

To Collect approximately 10 country-level tourism records from a public
tourism/informational website using requests and BeautifulSoup.

The scraped data will contain:
- Country
- Tourist Arrivals

The final dataset will be saved as scraped_data.csv

In [26]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

### Defining the webpage

In [39]:
url = "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2153606&lang=2&reg=48"

response = requests.get(url)

print("Status Code:", response.status_code)

Status Code: 200

If you get 200, continue.

### Creating the BeautifulSoup object

In [40]:
soup = BeautifulSoup(response.text, "html.parser")

print("BeautifulSoup object created successfully.")
print("Page title:", soup.title.get_text(strip=True))

BeautifulSoup object created successfully.
Page title: Press Release Page | Press Information Bureau

### Inspecting the webpage, Before Scraping

In [41]:
tables = soup.find_all("table")
print("Number of tables found:", len(tables))

Number of tables found: 7

In [43]:
for i, table in enumerate(tables):
    print(f"\nTABLE {i}")
    print(table.get_text(" | ", strip=True)[:1000])
    print("-" * 80)

TABLE 0
Year | FTAs | INDs | 2019 | 1,09,30,355 | 2,69,15,034 | 2022 | 64,37,467 | 2,16,02,734 | 2023 | 95,20,928 | 2,78,77,640 | 2024 | 99,51,722 | 3,08,85,048
--------------------------------------------------------------------------------

TABLE 1
S. No. | Country | 2019 | 2022 | 2023 | 2024 | 1 | United States | 15,12,032 | 14,03,399 | 16,91,498 | 18,04,586 | 2 | Bangladesh | 25,77,727 | 12,77,557 | 21,19,826 | 17,50,165 | 3 | United Kingdom | 10,00,292 | 6,41,051 | 9,20,591 | 10,22,587 | 4 | Australia | 3,67,241 | 3,76,898 | 4,56,167 | 5,18,205 | 5 | Canada | 3,51,859 | 2,89,259 | 3,85,938 | 4,76,273 | 6 | Malaysia | 3,34,579 | 1,26,192 | 2,62,458 | 3,07,526 | 7 | Sri Lanka | 3,30,861 | 1,83,459 | 2,80,327 | 2,81,827 | 8 | Germany | 2,64,973 | 1,41,425 | 2,23,575 | 2,56,348 | 9 | France | 2,47,238 | 1,20,282 | 1,88,981 | 2,06,855 | 10 | Singapore | 1,90,089 | 1,32,668 | 1,83,772 | 2,05,383 | 11 | Nepal | 1,64,040 | 1,38,203 | 1,95,445 | 2,02,501 | 12 | Japan | 2,38,903 | 64,196 | 1,50,521 | 1,94,875 | 13 | Russian Fed. | 2,51,319 | 97,911 | 1,64,125 | 1,60,188 | 14 | Italy | 1,28,572 | 62,226 | 1,16,031 | 1,42,239 | 15 | Thailand | 1,69,956 | 54,367 | 1,16,060 | 1,40,489 | 16 | Rep. of Korea | 1,49,445 | 49,423 | 97,726 | 1,12
--------------------------------------------------------------------------------

TABLE 2
S. No | Destination Country | 2019 | 2022 | 2023 | 2024 | 1 | United Arab Emirates | 63,85,504 | 60,40,269 | 72,17,736 | 77,87,496 | 2 | Saudi Arabia | 29,16,049 | 24,75,314 | 30,86,039 | 34,23,711 | 3 | United States | 19,38,302 | 17,27,754 | 20,54,369 | 21,43,909 | 4 | Thailand | 17,43,261 | 9,51,736 | 14,80,104 | 19,08,520 | 5 | Singapore | 15,97,707 | 10,12,812 | 13,83,312 | 15,34,984 | 6 | United Kingdom | 8,25,565 | 9,52,489 | 12,73,126 | 13,22,848 | 7 | Qatar | 11,37,339 | 9,10,276 | 11,25,267 | 11,40,407 | 8 | Canada | 6,34,460 | 7,79,278 | 9,88,362 | 9,45,652 | 9 | Kuwait | 9,84,658 | 8,51,588 | 8,36,543 | 9,06,965 | 10 | Oman | 9,40,911 | 7,44,022 | 8,12,407 | 8,64,251 | 11 | Malaysia | 7,75,286 | 3,08,129 | 5,04,993 | 7,65,344 | 12 | Australia | 5,89,539 | 4,89,404 | 6,22,068 | 6,61,405 | 13 | Bangladesh | 5,00,488 | 4,72,491 | 6,17,789 | 5,55,680 | 14 | Indonesia | 3,40,915 | 1,67,463 | 3,78,662 | 4,98,675 | 15 | Sri Lanka | 4,02,240 | 1,46,161 | 3,24,024 | 4,30,492 | 16 |
--------------------------------------------------------------------------------

TABLE 3
Ministry of Tourism | FOREIGN TOURISTS’ ARRIVALS AND INDIAN VISITING ABROAD | Posted On:
                        07 AUG 2025 4:15PM by PIB Delhi | The total number of Foreign Tourist Arrivals (FTAs) in India and Indian Nationals’ Departures (INDs) from India during 2019, 2022, 2023 and 2024 is as follows: | Year | FTAs | INDs | 2019 | 1,09,30,355 | 2,69,15,034 | 2022 | 64,37,467 | 2,16,02,734 | 2023 | 95,20,928 | 2,78,77,640 | 2024 | 99,51,722 | 3,08,85,048 | Source: Bureau of Immigration | The country-wise details of FTAs and INDs for the years 2019, 2022, 2023 and 2024 are placed at | Annexure | . | This information was given by Union Minister for Tourism and Culture Shri Gajendra Singh Shekhawat in a written reply in Rajya Sabha today. | **** | Sunil Kumar Tiwari | tourism4pib[at]gmail[dot]com | ANNEXURE | Country wise Foreign Tourist Arrivals (FTAs) during 2019, 2022, 2023 and 2024 | S. No. | Country | 2019 | 2022 | 2023 | 2024 | 1 | United States | 15,12,032 | 14,03,399 | 16,91,4
--------------------------------------------------------------------------------

TABLE 4
Year | FTAs | INDs | 2019 | 1,09,30,355 | 2,69,15,034 | 2022 | 64,37,467 | 2,16,02,734 | 2023 | 95,20,928 | 2,78,77,640 | 2024 | 99,51,722 | 3,08,85,048
--------------------------------------------------------------------------------

TABLE 5
S. No. | Country | 2019 | 2022 | 2023 | 2024 | 1 | United States | 15,12,032 | 14,03,399 | 16,91,498 | 18,04,586 | 2 | Bangladesh | 25,77,727 | 12,77,557 | 21,19,826 | 17,50,165 | 3 | United Kingdom | 10,00,292 | 6,41,051 | 9,20,591 | 10,22,587 | 4 | Australia | 3,67,241 | 3,76,898 | 4,56,167 | 5,18,205 | 5 | Canada | 3,51,859 | 2,89,259 | 3,85,938 | 4,76,273 | 6 | Malaysia | 3,34,579 | 1,26,192 | 2,62,458 | 3,07,526 | 7 | Sri Lanka | 3,30,861 | 1,83,459 | 2,80,327 | 2,81,827 | 8 | Germany | 2,64,973 | 1,41,425 | 2,23,575 | 2,56,348 | 9 | France | 2,47,238 | 1,20,282 | 1,88,981 | 2,06,855 | 10 | Singapore | 1,90,089 | 1,32,668 | 1,83,772 | 2,05,383 | 11 | Nepal | 1,64,040 | 1,38,203 | 1,95,445 | 2,02,501 | 12 | Japan | 2,38,903 | 64,196 | 1,50,521 | 1,94,875 | 13 | Russian Fed. | 2,51,319 | 97,911 | 1,64,125 | 1,60,188 | 14 | Italy | 1,28,572 | 62,226 | 1,16,031 | 1,42,239 | 15 | Thailand | 1,69,956 | 54,367 | 1,16,060 | 1,40,489 | 16 | Rep. of Korea | 1,49,445 | 49,423 | 97,726 | 1,12
--------------------------------------------------------------------------------

TABLE 6
S. No | Destination Country | 2019 | 2022 | 2023 | 2024 | 1 | United Arab Emirates | 63,85,504 | 60,40,269 | 72,17,736 | 77,87,496 | 2 | Saudi Arabia | 29,16,049 | 24,75,314 | 30,86,039 | 34,23,711 | 3 | United States | 19,38,302 | 17,27,754 | 20,54,369 | 21,43,909 | 4 | Thailand | 17,43,261 | 9,51,736 | 14,80,104 | 19,08,520 | 5 | Singapore | 15,97,707 | 10,12,812 | 13,83,312 | 15,34,984 | 6 | United Kingdom | 8,25,565 | 9,52,489 | 12,73,126 | 13,22,848 | 7 | Qatar | 11,37,339 | 9,10,276 | 11,25,267 | 11,40,407 | 8 | Canada | 6,34,460 | 7,79,278 | 9,88,362 | 9,45,652 | 9 | Kuwait | 9,84,658 | 8,51,588 | 8,36,543 | 9,06,965 | 10 | Oman | 9,40,911 | 7,44,022 | 8,12,407 | 8,64,251 | 11 | Malaysia | 7,75,286 | 3,08,129 | 5,04,993 | 7,65,344 | 12 | Australia | 5,89,539 | 4,89,404 | 6,22,068 | 6,61,405 | 13 | Bangladesh | 5,00,488 | 4,72,491 | 6,17,789 | 5,55,680 | 14 | Indonesia | 3,40,915 | 1,67,463 | 3,78,662 | 4,98,675 | 15 | Sri Lanka | 4,02,240 | 1,46,161 | 3,24,024 | 4,30,492 | 16 |
--------------------------------------------------------------------------------

## Finding the tourism table

In [44]:
tourism_table = tables[1]

print("Tourism table selected successfully.")

Tourism table selected successfully.

In [45]:
# Get all rows in the table
rows = tourism_table.find_all("tr")

print("Number of rows:", len(rows))

Number of rows: 65

In [46]:
# Inspecting first 5 rows
for row in rows[:5]:
    cells = row.find_all(["th", "td"])
    print([cell.get_text(" ", strip=True) for cell in cells])

['S. No.', 'Country', '2019', '2022', '2023', '2024']
['1', 'United States', '15,12,032', '14,03,399', '16,91,498', '18,04,586']
['2', 'Bangladesh', '25,77,727', '12,77,557', '21,19,826', '17,50,165']
['3', 'United Kingdom', '10,00,292', '6,41,051', '9,20,591', '10,22,587']
['4', 'Australia', '3,67,241', '3,76,898', '4,56,167', '5,18,205']

### Extracting the data

In [47]:
tourism_records = []

for row in rows:
    cells = row.find_all("td")
    
    if len(cells) >= 6:
        serial_no = cells[0].get_text(" ", strip=True)
        country = cells[1].get_text(" ", strip=True)
        arrivals_2019 = cells[2].get_text(" ", strip=True)
        arrivals_2022 = cells[3].get_text(" ", strip=True)
        arrivals_2023 = cells[4].get_text(" ", strip=True)
        arrivals_2024 = cells[5].get_text(" ", strip=True)
        
        tourism_records.append({
            "Country": country,
            "FTA_2019": arrivals_2019,
            "FTA_2022": arrivals_2022,
            "FTA_2023": arrivals_2023,
            "FTA_2024": arrivals_2024
        })

print("Records collected:", len(tourism_records))

Records collected: 65

### Creating Data Frame

In [48]:
tourism_df = pd.DataFrame(tourism_records)

tourism_df.head(15)

           Country   FTA_2019   FTA_2022   FTA_2023   FTA_2024
0          Country       2019       2022       2023       2024
1    United States  15,12,032  14,03,399  16,91,498  18,04,586
2       Bangladesh  25,77,727  12,77,557  21,19,826  17,50,165
3   United Kingdom  10,00,292   6,41,051   9,20,591  10,22,587
4        Australia   3,67,241   3,76,898   4,56,167   5,18,205
5           Canada   3,51,859   2,89,259   3,85,938   4,76,273
6         Malaysia   3,34,579   1,26,192   2,62,458   3,07,526
7        Sri Lanka   3,30,861   1,83,459   2,80,327   2,81,827
8          Germany   2,64,973   1,41,425   2,23,575   2,56,348
9           France   2,47,238   1,20,282   1,88,981   2,06,855
10       Singapore   1,90,089   1,32,668   1,83,772   2,05,383
11           Nepal   1,64,040   1,38,203   1,95,445   2,02,501
12           Japan   2,38,903     64,196   1,50,521   1,94,875
13    Russian Fed.   2,51,319     97,911   1,64,125   1,60,188
14           Italy   1,28,572     62,226   1,16,031   1,42,239

### Keeping 10 records

In [49]:
tourism_df = tourism_df.head(10).copy()

tourism_df

          Country   FTA_2019   FTA_2022   FTA_2023   FTA_2024
0         Country       2019       2022       2023       2024
1   United States  15,12,032  14,03,399  16,91,498  18,04,586
2      Bangladesh  25,77,727  12,77,557  21,19,826  17,50,165
3  United Kingdom  10,00,292   6,41,051   9,20,591  10,22,587
4       Australia   3,67,241   3,76,898   4,56,167   5,18,205
5          Canada   3,51,859   2,89,259   3,85,938   4,76,273
6        Malaysia   3,34,579   1,26,192   2,62,458   3,07,526
7       Sri Lanka   3,30,861   1,83,459   2,80,327   2,81,827
8         Germany   2,64,973   1,41,425   2,23,575   2,56,348
9          France   2,47,238   1,20,282   1,88,981   2,06,855

### Convert arrival values to numbers

Currently they contain commas:
*18,04,586*

Needed:
*1804586*

In [50]:
arrival_columns = [
    "FTA_2019",
    "FTA_2022",
    "FTA_2023",
    "FTA_2024"
]

for column in arrival_columns:
    tourism_df[column] = (
        tourism_df[column]
        .str.replace(",", "", regex=False)
        .str.strip()
    )
    
    tourism_df[column] = pd.to_numeric(
        tourism_df[column],
        errors="coerce"
    )

### Check the cleaned data

In [51]:
tourism_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Country   10 non-null     object
 1   FTA_2019  10 non-null     int64
 2   FTA_2022  10 non-null     int64
 3   FTA_2023  10 non-null     int64
 4   FTA_2024  10 non-null     int64
dtypes: int64(4), object(1)
memory usage: 532.0+ bytes

In [52]:
tourism_df

          Country  FTA_2019  FTA_2022  FTA_2023  FTA_2024
0         Country      2019      2022      2023      2024
1   United States   1512032   1403399   1691498   1804586
2      Bangladesh   2577727   1277557   2119826   1750165
3  United Kingdom   1000292    641051    920591   1022587
4       Australia    367241    376898    456167    518205
5          Canada    351859    289259    385938    476273
6        Malaysia    334579    126192    262458    307526
7       Sri Lanka    330861    183459    280327    281827
8         Germany    264973    141425    223575    256348
9          France    247238    120282    188981    206855

In [54]:
# Check for missing values
missing_values = tourism_df.isnull().sum()
print("Missing values per column:")
print(missing_values)

Missing values per column:
Country     0
FTA_2019    0
FTA_2022    0
FTA_2023    0
FTA_2024    0
dtype: int64

In [55]:
# Check for duplicate rows
print("Duplicate rows:", tourism_df.duplicated().sum())

Duplicate rows: 0

### Saving CSV

In [57]:
tourism_df.to_csv("scraped_data.csv", index=False)
print("scraped_data.csv saved successfully.")

scraped_data.csv saved successfully.

In [59]:
# Verify the saved CSV file
pd.read_csv("scraped_data.csv")

          Country  FTA_2019  FTA_2022  FTA_2023  FTA_2024
0         Country      2019      2022      2023      2024
1   United States   1512032   1403399   1691498   1804586
2      Bangladesh   2577727   1277557   2119826   1750165
3  United Kingdom   1000292    641051    920591   1022587
4       Australia    367241    376898    456167    518205
5          Canada    351859    289259    385938    476273
6        Malaysia    334579    126192    262458    307526
7       Sri Lanka    330861    183459    280327    281827
8         Germany    264973    141425    223575    256348
9          France    247238    120282    188981    206855

In [61]:
# ============================================================
# BONUS ANALYSIS: HOTEL BOOKINGS vs TOURISM ARRIVALS
# ============================================================

import pandas as pd

# Load datasets
hotel_df = pd.read_csv("cleaned_hotel_bookings.csv")
tourism_df = pd.read_csv("scraped_data.csv")

# Map hotel dataset country codes to tourism country names
country_mapping = {
    "USA": "United States",
    "GBR": "United Kingdom",
    "AUS": "Australia",
    "CAN": "Canada",
    "MYS": "Malaysia",
    "LKA": "Sri Lanka",
    "DEU": "Germany",
    "FRA": "France",
    "BGD": "Bangladesh",
    "IND": "India",
    "ESP": "Spain",
    "ITA": "Italy",
    "NLD": "Netherlands",
    "IRL": "Ireland",
    "JPN": "Japan",
    "RUS": "Russian Fed.",
    "THA": "Thailand",
    "SGP": "Singapore",
    "KOR": "Rep. of Korea",
    "CHE": "Switzerland",
    "SWE": "Sweden",
    "NOR": "Norway",
    "DNK": "Denmark",
    "BEL": "Belgium",
    "AUT": "Austria",
    "PRT": "Portugal",
    "POL": "Poland",
    "BRA": "Brazil",
    "ARG": "Argentina",
    "CHN": "China",
    "HKG": "Hong Kong",
    "ISR": "Israel",
    "ZAF": "South Africa",
    "NZL": "New Zealand"
}

# Create readable country names
hotel_df["Country_Name"] = hotel_df["country"].map(country_mapping)

# Count hotel bookings by country-
hotel_bookings_country = (
    hotel_df
    .groupby("Country_Name", dropna=True)
    .size()
    .reset_index(name="Hotel_Bookings")
)

# Merge with tourism data
bonus_df = pd.merge(
    hotel_bookings_country,
    tourism_df,
    left_on="Country_Name",
    right_on="Country",
    how="inner"
)

# Calculate booking share and comparison metric
bonus_df["Hotel_Booking_Rank"] = (
    bonus_df["Hotel_Bookings"]
    .rank(method="min", ascending=False)
    .astype(int)
)

bonus_df["Tourism_Arrival_Rank_2024"] = (
    bonus_df["FTA_2024"]
    .rank(method="min", ascending=False)
    .astype(int)
)

# Difference between tourism rank and hotel booking rank
bonus_df["Rank_Difference"] = (
    bonus_df["Tourism_Arrival_Rank_2024"]
    - bonus_df["Hotel_Booking_Rank"]
)

# Sort by hotel bookings
bonus_df = bonus_df.sort_values(
    "Hotel_Bookings",
    ascending=False
).reset_index(drop=True)

# Display result
print("=" * 70)
print("BONUS ANALYSIS: HOTEL BOOKINGS vs TOURISM ARRIVALS")
print("=" * 70)

display(
    bonus_df[
        [
            "Country_Name",
            "Hotel_Bookings",
            "FTA_2019",
            "FTA_2022",
            "FTA_2023",
            "FTA_2024",
            "Hotel_Booking_Rank",
            "Tourism_Arrival_Rank_2024",
            "Rank_Difference"
        ]
    ]
)

# Save bonus analysis
bonus_df.to_csv(
    "hotel_bookings_vs_tourism_bonus.csv",
    index=False
)

print("\nBonus analysis saved successfully as:")
print("hotel_bookings_vs_tourism_bonus.csv")
print("\nCountries successfully matched:", len(bonus_df))

======================================================================
BONUS ANALYSIS: HOTEL BOOKINGS vs TOURISM ARRIVALS
======================================================================

,Country_Name,Hotel_Bookings,FTA_2019,FTA_2022,FTA_2023,FTA_2024,Hotel_Booking_Rank,Tourism_Arrival_Rank_2024,Rank_Difference
0,United Kingdom,10422,1000292,641051,920591,1022587,1,3,2
1,France,8823,247238,120282,188981,206855,2,8,6
2,Germany,5385,264973,141425,223575,256348,3,7,4
3,United States,1871,1512032,1403399,1691498,1804586,4,1,-3
4,Australia,378,367241,376898,456167,518205,5,4,-1
5,Malaysia,24,334579,126192,262458,307526,6,5,-1
6,Bangladesh,10,2577727,1277557,2119826,1750165,7,2,-5
7,Sri Lanka,6,330861,183459,280327,281827,8,6,-2

Bonus analysis saved successfully as:
hotel_bookings_vs_tourism_bonus.csv

Countries successfully matched: 8